### ISSUE TITLE
files get renamed on opening

### ISSUE THREAD

**Issue by annamorphism** [DDMAL/Neon#947]
Here's a bunch of files I uploaded all at once:
![image](https://user-images.githubusercontent.com/67451875/182186761-494906a4-540d-4a3d-9179-d44a95bcea3b.png)

Command-click, I open all 16. Results:
1r: correct
3r, 4r, 7r: correct
8v: right neumes, but *labelled* 1r in upper left
1v, everything else: labelled 1r, no MEI apparently.
(Same results for shift click.)

Opening the pages individually:
1r,3r,4r,7r still correct
1v, 2v, 3v,4v, 5r, 5v, 6r, 6v, 7v, 8r, 9r: now all have neumes, but labeled 1r
8v:  neumeless for some reason the first time, but neumes loaded when I tried it again. Still labelled 1r.

Possibly related: when I tried uploading 3r and 5r (a second time) I got an error: 
![image](https://user-images.githubusercontent.com/67451875/182190232-e3de7206-8c78-4482-bcc2-09232e1ad2f7.png)

However, they both had the same behaviour as previously: 3r is normal, 5r has neumes but is labelled 1r.

**Comment by chetbae** [comment]
Oh this is strange! @annamorphism would you mind attaching the png and mei files for 1r and 8v for me to test with?

**Comment by annamorphism** [comment]
@chetbae I am going to do a little experimenting first--I don't think it's those particular files, but probably something to do with my workflow. Going to see whether I can replicate it....

**Comment by annamorphism** [comment]
Ok so there are at least two problems going on. 
One is that when I try to open a bunch of pages at once, many of them stall--so I get the image, and I get the Neon buttons and I can press them, but I can't actually interact with the MEI file, or even zoom, for that matter. This is easily resolved by just reloading the page, but it might be nice to throw some sort of message when this happens so the user isn't sitting there waiting for something that's not actually going to load. 

When I do reload them they still like to be named 1r. More investigation required.

**Comment by annamorphism** [comment]
I thought maybe it had to do with opening a group including 1r, but I can open say, 10r-15r and still get most of them named 1r. Deleted 1r from the set--files still like to be named 1r.

And it gets weirder! I uploaded some files (11-13, NOT 1r) to a new browser (Chrome) just to see what it would call them in the absence of that file. Good news, 13v is 13v...but a lot of the pages crash when you try to open them all at once. And when, say, 13r crashes, the tab with 13v ALSO crashes, even if it loaded before!

**Comment by annamorphism** [comment]
ok so in Chrome only one Neon tab wants to be opened at a time??? When I have more than one open they all crash.  This is particularly strange since it doesn't happen this way in Opera, which usually behaves identically to Chrome. 

Then when I do reload the sad tabs:
11r (the first one I opened) is "named" 11r
Everything else seems to be named 13v (the first page I reloaded successfully.) 

they have the right MEI, just the wrong name:
![image](https://user-images.githubusercontent.com/67451875/182461484-324ceace-7c96-4a41-a0bb-19d3ff0fbc6e.png)

**Comment by yinanazhou** [comment]
Hi @annamorphism, we have merged the fix for this issue. Could you please confirm that this issue can be closed now?

**Comment by annamorphism** [comment]
Hmm, they still seems to get renamed--here's several "1r" pages:
![image](https://user-images.githubusercontent.com/67451875/190470087-db228076-2f6b-4af2-a141-6b0c47942090.png)
![image](https://user-images.githubusercontent.com/67451875/190470212-b7cdb546-9f52-4d4e-89dd-7f32e982166e.png)
![image](https://user-images.githubusercontent.com/67451875/190470484-1501ef87-4e7d-4467-80e0-84ce2a9eb22e.png)

Or does the fix only apply to new uploads? 
Testing other things I already uploaded, they do something different: they get the right name, but crash when opening more than one. 
![image](https://user-images.githubusercontent.com/67451875/190474659-427f20da-94ae-4b7c-9136-8adb01db4d1e.png)
![image](https://user-images.githubusercontent.com/67451875/190475186-a8c789bf-3deb-442c-9fbb-19634a6755d8.png)

No idea why some folios have this behaviour and not others, but maybe if neither happens to new uploads it doesn't matter. 
Will upload some new files and see what happens.

**Comment by yinanazhou** [comment]
Thanks @annamorphism, I don't think the fix would work on the old files though. I hope the new files works well.

**Comment by annamorphism** [comment]
I think the new uploads don't have the renaming issue.
However, the issue where opening multiple folios at once causes crashing is still happening (one folio will load, all other Neon tabs, including the dashboard, will crash and need to be refreshed.) 
I am also experiencing some sort of hang on some duplicated uploads, but it may only be ones that duplicate older uploads. I think new uploads can successfully handle duplicates (though they seem to crash more? maybe it's an illusion.) Will test some more and report. 
-I also get an error if I try to upload a duplicate that already has e.g. (1) as part of the file name: 
![image](https://user-images.githubusercontent.com/67451875/190503893-7978914e-f3ce-4caf-83d9-02c6ca8d144c.png)
These are not part of the original issue, though!

**Comment by yinanazhou** [comment]
Hi @annamorphism I'd like to follow up on this issue. From the discussion above, the original issue seems to be addressed. Can we close this issue now?

**Comment by annamorphism** [comment]
@yinanazhou a lot has changed about the interface since I wrote this!

What I experienced way back in the fall:
-Something about renamed files that was resolved upthread.
-An issue where opening multiple folios at once causes crashing.  This is I think totally resolved in the new interface.
-Assorted issues about duplicated names in files: this is much improved, though I did find a few small things just now that I will put in a separate issue. Closing this issue.
